apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/elroy-haw/homelab-sandbox.git
    targetRevision: HEAD
    path: kubernetes/argocd/instances/overlays/cluster-0
  destination:
    namespace: argocd
    server: in-cluster
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
